In [4]:
loans = [500, 0, 700, 0, 650, 0, 800, 0]

total = sum(loans)
t=0
for v in loans:
    t += v
print(t)

print(total)

repayments = []

for v in loans:
    repayments.append(v * 1.05)

print(repayments)

i = 0
while i < len(repayments):
    print(repayments[i])
    i+=1

    



2650
2650
[525.0, 0.0, 735.0, 0.0, 682.5, 0.0, 840.0, 0.0]
525.0
0.0
735.0
0.0
682.5
0.0
840.0
0.0


In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr)



from datetime import datetime

print(datetime.now())



import random
print(random.random())



[10 20 30 40 50]
2026-07-25 18:33:59.394909
0.294570077372163


In [19]:
nums = [10, 20, 30, 40, 50]

arr = np.array(nums)
print(arr.shape)


arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr.shape)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
comb_arr = arr1 + arr2
print(comb_arr)

arr_mult = arr1 * 3
print(arr_mult)



(5,)
(3, 3)
[5 7 9]
[3 6 9]


In [40]:

from datetime import datetime, time, timedelta
import os
import pandas as pd

cur_date = datetime.now().date()
cur_time = datetime.now().time()


print(cur_time)

spy_dir = "~/python-projects/ed-backtest/backtester/data/sp_constituents/SPY.csv"

path = os.path.join(spy_dir)

data = pd.read_csv(path)
data['Date'] = pd.to_datetime(data['Date'], utc=True)


# Check if the latest SPY data entry is today's date.
# If it isn't, and the time is past 21:30 (market close), update all CSVs.
if data['Date'].iloc[-1].date() != cur_date and cur_time >= time(21, 30):
    end_date = str(cur_date)




# If the last data point is Yesterday's data, and market isn't closed for today, continue
elif data['Date'].iloc[-1].date() == cur_date - timedelta(days=1) and cur_time < time(21, 30):
    pass

# If the last data point is not Yesterday's close, update to latest available data:
elif data['Date'].iloc[-1].date() != cur_date - timedelta(days=1) and cur_time < time(21, 30):
    end_date = str(cur_date - timedelta(days=1))

    # UPDATE TO YESTERDAY




print(cur_date)
print(cur_date - timedelta(days=1))



tickers = ['SPY', 'VIX', 'AAPL', 'MSFT']
nq_tickers = ['QQQ', 'SPY', 'MSFT', 'TSLA']
ticker_list = tickers + nq_tickers
ticker_list = set(ticker_list)
print(ticker_list)




13:00:55.771830
2026-07-26
2026-07-25
{'MSFT', 'VIX', 'SPY', 'QQQ', 'AAPL', 'TSLA'}


In [ ]:
import numpy as np

rt_arr = np.array([5, 8, 3, 10, 6])

print(rt_arr.shape)
print(f"Mean Returns: ${np.mean(rt_arr):.2f}")
print(f"Highest Return: ${np.max(rt_arr)}")
print(f"Std: {np.std(rt_arr):.2f}")

(5,)
Mean Returns: $6.40
Highest Return: $10
Std: 2.42


In [ ]:
import pandas as pd
#Series Stuff I've not done somehow
# - pivot()
# - melt()


explicit_labels = ['Apple', 'Banana', 'Cherry']
fruits = pd.Series([5, 10, 15], index=explicit_labels)


d = {
    'USA': 100,
    'China': 300,
    'India': 225
}
population = pd.Series(d)

population.name = 'Population'
population.index.name = 'Country'
print(population)



Country
USA      100
China    300
India    225
Name: Population, dtype: int64


In [ ]:
import pandas as pd

# Dataframe stuff I somehow havent done before

# Specify column names
df = pd.DataFrame(data, columns=['City', 'Name', 'Age'])

# Specify row labels
df = pd.DataFrame(data, index=['a', 'b', 'c'])

# for columns its obvious, for labels just remember when to use loc and iloc
df['City'].iloc[0]
df['City'].loc['a']


      City  Name  Age
0      NaN   NaN  NaN
1      NaN   NaN  NaN
2      NaN   NaN  NaN
3      NaN   NaN  NaN
4      NaN   NaN  NaN
...    ...   ...  ...
5416   NaN   NaN  NaN
5417   NaN   NaN  NaN
5418   NaN   NaN  NaN
5419   NaN   NaN  NaN
5420   NaN   NaN  NaN

[5421 rows x 3 columns]


In [69]:
import pandas as pd

d = {
    'Movie': ['Inception', 'Matrix', 'Interstellar'],
    'Rating': [9, 8, 9.5]
}
movies_df = pd.DataFrame(d, columns=['Rating', 'Movie'])
print(movies_df)

movies = movies_df['Movie']
print(movies)
print(movies_df.iloc[0])


   Rating         Movie
0     9.0     Inception
1     8.0        Matrix
2     9.5  Interstellar
0       Inception
1          Matrix
2    Interstellar
Name: Movie, dtype: str
Rating          9.0
Movie     Inception
Name: 0, dtype: object


In [70]:
# Common data manipulation techniques:

import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [24, 27, 22, 32, 29],
    'Grade': [88, 92, 95, 70, 85]
}
df = pd.DataFrame(data)
print(df)


      Name  Age  Grade
0    Alice   24     88
1      Bob   27     92
2  Charlie   22     95
3    David   32     70
4      Eva   29     85


In [73]:
print(df.iloc[1:4])

high_grades = df[df['Grade'] > 90]
print(high_grades)

df['Passed'] = df['Grade'] >= 75
print(df)



      Name  Age  Grade
1      Bob   27     92
2  Charlie   22     95
3    David   32     70
      Name  Age  Grade
1      Bob   27     92
2  Charlie   22     95
      Name  Age  Grade  Passed
0    Alice   24     88    True
1      Bob   27     92    True
2  Charlie   22     95    True
3    David   32     70   False
4      Eva   29     85    True


In [ ]:
# Merging and joining DataFrames
